### PR TITLE
updated german language file

### PR DESCRIPTION
**Pull request by alias-bitsignal**

### CODE REVIEW

**Comment by redDwarf03** [comment]
hello but I don't understand your different commits when I see the final files changed

**Comment by alias-bitsignal** [comment]
I copied and pasted your language file because I liked certain phrases more than mine while I didn't notice that some phrases weren't translated.

**Comment by redDwarf03** [comment]
Ok. So, could you please send me your final files per discord

**Comment by alias-bitsignal** [comment]
this is the new updated final German translation file:
https://github.com/alias-bitsignal/my_bismuth_wallet/blob/master/lib/l10n/intl_de.arb

**Pull request closed without merging**
